#This file is part of The NX GApps Project script of @AlexLartsev19.
#
#    The NX GApps Project scripts are free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    These scripts are distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
### DO NOT EDIT THIS FILE ###
include scripts/main.mk
### DO NOT EDIT THIS FILE ###
